[package]
name = "pine5-gateway-linker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pine5-gateway-data = { path = "../data/" }
paho-mqtt = "0.11.1"
thiserror = "1"
